name: Sincronizador Frota

on:
  schedule:
    # Roda a cada 20 minutos (GitHub pode atrasar um pouco, é normal)
    - cron: '*/20 * * * *'
  workflow_dispatch: # Permite você clicar num botão "Rodar Agora" se quiser

jobs:
  executar-robo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Bibliotecas
        run: |
          pip install -r requirements.txt

      - name: Rodar Robô
        env:
          SASCAR_USER: ${{ secrets.SASCAR_USER }}
          SASCAR_PASS: ${{ secrets.SASCAR_PASS }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python jobs/sync_job.py
